(* red-Parity-Intervals13.ml *)
open Avalues1 (* avalues.ml of Parity    *)
(* \gamma(BOT)  = {_O_(a)}                                         *)
(* \gamma(ODD)  = { 2n+1\in[min_int,max_int] | n\in Z } U {_O_(a)} *)
(* \gamma(EVEN) = { 2n\in[min_int,max_int] | n\in Z } U {_O_(a)}   *)
(* \gamma(TOP)  = [min_int,max_int] U {_O_(a),_O_(i)}              *)
open Avalues3 (* avalues.ml of Intervals *)
(* gamma (a,b) = [a,b] U {_O_(a), _O_(i)} when min_int <= a <= b <= max_int *)
(*             = {_O_(a), _O_(i)}         when a = max_int > min_int = b    *)
(* reduction of parity and intervals *)
let reduce (p, i) =
if (Avalues1.eq p (Avalues1.bot ())) then ((Avalues1.bot ()), (Avalues3.bot ()))
else if (Avalues1.eq p (Avalues1.f_NAT "1")) then (p, (reduce_odd i))
else if (Avalues1.eq p (Avalues1.f_NAT "0")) then (p, (reduce_even i))
else if ((Avalues3.parity i) = 0) then ((Avalues1.f_NAT "0"), i) 
else if ((Avalues3.parity i) = 1) then ((Avalues1.f_NAT "1"), i) 
else (p, i)