# ${EXAMPLES}/makefile

SHELL = tcsh

.PHONY : examples
examples :
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example00.sil; ./a.out ${EXAMPLES}/example00.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example01.sil; ./a.out ${EXAMPLES}/example01.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example02.sil; ./a.out ${EXAMPLES}/example02.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example03.sil; ./a.out ${EXAMPLES}/example03.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example04.sil; ./a.out ${EXAMPLES}/example04.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example05.sil; ./a.out ${EXAMPLES}/example05.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example06.sil; ./a.out ${EXAMPLES}/example06.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example07.sil; ./a.out ${EXAMPLES}/example07.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example08.sil; ./a.out ${EXAMPLES}/example08.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example09.sil; ./a.out ${EXAMPLES}/example09.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example10.sil; ./a.out ${EXAMPLES}/example10.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example11.sil; ./a.out ${EXAMPLES}/example11.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example12.sil; ./a.out ${EXAMPLES}/example12.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example13.sil; ./a.out ${EXAMPLES}/example13.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example14.sil; ./a.out ${EXAMPLES}/example14.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example15.sil; ./a.out ${EXAMPLES}/example15.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example16.sil; ./a.out ${EXAMPLES}/example16.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example17.sil; ./a.out ${EXAMPLES}/example17.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example18.sil; ./a.out ${EXAMPLES}/example18.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example19.sil; ./a.out ${EXAMPLES}/example19.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example20.sil; ./a.out ${EXAMPLES}/example20.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example21.sil; ./a.out ${EXAMPLES}/example21.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example22.sil; ./a.out ${EXAMPLES}/example22.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example23.sil; ./a.out ${EXAMPLES}/example23.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example24.sil; ./a.out ${EXAMPLES}/example24.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example25.sil; ./a.out ${EXAMPLES}/example25.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example26.sil; ./a.out ${EXAMPLES}/example26.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example27.sil; ./a.out ${EXAMPLES}/example27.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example28.sil; ./a.out ${EXAMPLES}/example28.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example29.sil; ./a.out ${EXAMPLES}/example29.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example30.sil; ./a.out ${EXAMPLES}/example30.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example31.sil; ./a.out ${EXAMPLES}/example31.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example32.sil; ./a.out ${EXAMPLES}/example32.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example33.sil; ./a.out ${EXAMPLES}/example33.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example34.sil; ./a.out ${EXAMPLES}/example34.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example35.sil; ./a.out ${EXAMPLES}/example35.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example36.sil; ./a.out ${EXAMPLES}/example36.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example37.sil; ./a.out ${EXAMPLES}/example37.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example38.sil; ./a.out ${EXAMPLES}/example38.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example39.sil; ./a.out ${EXAMPLES}/example39.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example40.sil; ./a.out ${EXAMPLES}/example40.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example41.sil; ./a.out ${EXAMPLES}/example41.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example42.sil; ./a.out ${EXAMPLES}/example42.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example43.sil; ./a.out ${EXAMPLES}/example43.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example44.sil; ./a.out ${EXAMPLES}/example44.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example45.sil; ./a.out ${EXAMPLES}/example45.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example46.sil; ./a.out ${EXAMPLES}/example46.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example47.sil; ./a.out ${EXAMPLES}/example47.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example48.sil; ./a.out ${EXAMPLES}/example48.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example49.sil; ./a.out ${EXAMPLES}/example49.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example50.sil; ./a.out ${EXAMPLES}/example50.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example51.sil; ./a.out ${EXAMPLES}/example51.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example52.sil; ./a.out ${EXAMPLES}/example52.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example53.sil; ./a.out ${EXAMPLES}/example53.sil
	@echo ""; echo "** Input file:";cat  ${EXAMPLES}/example54.sil; ./a.out ${EXAMPLES}/example54.sil

.PHONY : clean-examples
clean-examples :
	/bin/rm -f example*.sil~