(* red-Errors-Intervals12.ml *)
open Avalues1 (* avalues.ml of Errors *)
(* gamma(NER) = [min_int,max_int]                    *)
(* gamma(AER) = [min_int,max_int] U {_O_(a)}         *)
(* gamma(IER) = [min_int,max_int] U {_O_(i)}         *)
(* gamma(ERR) = [min_int,max_int] U {_O_(a), _O_(i)} *)
open Avalues2 (* avalues.ml of Intervals *)
(* gamma (a,b) = [a,b] U {_O_(a), _O_(i)} when min_int <= a <= b <= max_int *)
(*             = {_O_(a), _O_(i)}         when a = max_int > min_int = b    *)
let reduce (a, b) = (a, b)